### ISSUE TITLE
NoSuchMethodException when creating entry-point for a game

### ISSUE THREAD

**Issue by TimMaasGeesteranus** [han-yaeger/yaeger#151] opened 2021-01-06 19:53 UTC
This issue can be reproducted by creating a package for your game and creating the entry-point for the game

```
public class MyGame extends YaegerGame {
    @Override
    protected void setupGame() {
        setGameTitle("MyGame");
        setSize(new Size(500, 500));
    }

    @Override
    protected void setupScenes() {

    }
}
```

The exception:
```
Exception in Application start method
Exception in thread "main" java.lang.NoSuchMethodException: com.github.test.game.MyGame.main([Ljava.lang.String;)
	at java.base/java.lang.Class.getMethod(Class.java:2122)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:110)
```

**Comment by meronbrouwer** [comment] 2021-01-06 20:41
I guess this is caused by the absence of a `public static void main(String[] args)` method. Such a method is required to start the application.

This is a nice one to add to the FAQ, since more students might run into this.

**Comment by TimMaasGeesteranus** [comment] 2021-01-07 08:42
This must have been changed somewhere in the latest commits. When I run the code example above in my version of Yaeger from december 29th, there is no exception and the game will start.

**Comment by meronbrouwer** [comment] 2021-01-11 08:12
That is peculiar, since it lacks the main method and will therefor receive a noSuchMethodException. But besides that, the fact that the exception is thrown is expected behaviour. So I will close this issue.

**Closed** 2021-01-12 09:59 UTC
Labels: bug
