### ISSUE TITLE
Bug: setAutoCycle animates up to a certain row instead of one single row

### ISSUE THREAD

**Issue by fritzvd** [han-yaeger/yaeger#240] opened 2022-03-30 08:07 UTC
The documentation for `protected void setAutoCycle​(long interval, int row)` in DynamicSpriteEntity claims to be doing:
_Set the interval at which the sprite should be automatically cycled. The sprite will cycle through one row of sprites, from left to right._

However it seems to be animating everything up to the row that you pass as the `int row` argument

**Comment by SimonVreman** [comment] 2022-06-22 18:48
Tested on dev branch, cannot reproduce. Observation for the following sprite:
<img width="237" alt="numbersprite" src="https://user-images.githubusercontent.com/35310171/175107772-59791744-f867-4e5f-9ad6-953c8d63346e.png">
- `setAutoCycle​(long interval, 0)` animates numbers 1, 2 and 3 and then loops
- `setAutoCycle​(long interval, 1)` animates numbers 4, 5 and 6 and then loops
- `setAutoCycle​(long interval, 2)` animates numbers 7, 8 and 9 and then loops
Appears to work as expected. Maybe caused by something else?

**Comment by meronbrouwer** [comment] 2022-06-25 18:18
Hi Simon, good to hear from you again. Hows life at uni?

I also thought this one could not be reproduced, so its probably something else.

**Comment by fritzvd** [comment] 2022-06-25 19:48
Thanks for following up. I might be able to send you the source code they contained the bug. Would that be helpful?

**Comment by meronbrouwer** [comment] 2022-06-25 20:21
Yes!

**Comment by SimonVreman** [comment] 2022-07-06 13:03
Life at uni is good, passed the first year. If the code still needs to be looked at I could do it.

**Comment by fritzvd** [comment] 2022-07-06 19:26
https://github.com/hanaim-oopd-1da/beroepsproduct-yaeger-lars-meijrink-en-thomas-droppert/blob/b189e4c84146ee78b283318cfa2583aab3b7952a/src/main/java/com/github/hanyaeger/tutorial/CHARACTER/Player.java#L45-L51

I think this comment and lines of code describe the problem. So in this revision it must still be going wrong. 🤷

**Comment by meronbrouwer** [comment] 2022-07-07 11:28
> Life at uni is good, passed the first year. If the code still needs to be looked at I could do it.

If you're willing, feel free to pick this one up. If not, I'll do it.

**Comment by SimonVreman** [comment] 2022-07-08 10:00
Yes, but the linked repo is private.

**Comment by SimonVreman** [comment] 2022-07-10 08:01
Yes please

**Comment by fritzvd** [comment] 2022-07-10 08:58
I can also give you access to original repo. Give me a sec

**Comment by meronbrouwer** [comment] 2022-07-10 18:02
Did it work out with the access rights?

**Comment by SimonVreman** [comment] 2022-07-10 18:06
Don’t have access yet

**Comment by fritzvd** [comment] 2022-07-10 19:20
.. sorry just added you a minute ago.

**Comment by SimonVreman** [comment] 2022-07-12 18:28
Investigated, works as expected. The behaviour they were noticing is most likely due to line 62 of the same file: `setCurrentFrameIndex(0);`. When autocycling a row it increases until reaching the last frame and then it goes to the first frame of the row again. Setting the current frame to zero without turning off autocycle using `setAutoCycle(0)` or something else will cause it to start from the very first frame of the sprite and continue until the last frame of the row. Then it recovers and goes to the first frame of the row again. 

Also, the `onPressedKeysChange` event is called once, then not for a bit (300 ms or so on my mac) and then continuously while holding the key. This caused their autocycle to restart and not actually animate properly. Not well documented in the version of the framework they used but is documented now.

This issue can be closed.

**Comment by meronbrouwer** [comment] 2022-07-13 18:07
Thanks for your investigations and insights. I'm currently working on issue #239, which will add the possibility to define explicit animations that make up a certain part of the spritesheet.  It should simplify the usage of spritesheets significantly. 

I'll close this issue.

**Closed by meronbrouwer** 2022-07-13 18:07 UTC
Labels: bug
